name: Seasonal Anime Update

on:
  schedule:
    - cron: '0 0 1 */3 *'
  workflow_dispatch: 

jobs:
  run-seasonal-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Run seasonal anime update script
        run: tsx backend/cron.ts
